// examples/cgrid-ext-react/src/App.tsx
import { VelocityExtGrid } from './VelocityExtGrid';

export function App() {
  return (
    <div className="page">
      <header className="page-header">
        <h1>VelocityGridExt · React</h1>
        <p>
          Installed from <code>dist/tarballs/*.tgz</code>, not the monorepo workspace.
        </p>
      </header>
      <VelocityExtGrid />
    </div>
  );
}

// examples/cgrid-ext-angular/src/app/app.ts
import { Component } from '@angular/core';
import { VelocityExtGrid } from './velocity-ext-grid';

@Component({
  selector: 'app-root',
  standalone: true,
  imports: [VelocityExtGrid],
  template: `
    <div class="page">
      <header class="page-header">
        <h1>VelocityGridExt · Angular</h1>
        <p>
          Installed from <code>dist/tarballs/*.tgz</code>, not the monorepo workspace.
        </p>
      </header>
      <app-velocity-ext-grid />
    </div>
  `,
})
export class App {}
